edgexfoundry/device-bacnet-c

res/ip/configuration.toml
src/c/main.c

Signed-off-by: Christoffer Christensen <gofling2@hotmail.com>

Get BBMD configuration entries from driver (#3)

---

README.md
src/c/CMakeLists.txt

Use CSDK_DIR to locate the SDK. Addresses #6

Allow build using local CSDK (#6)

---

src/c/main.c

Signed-off-by: Christoffer Christensen <gofling2@hotmail.com>

Change default port to BAC0

---

README.md
docs/device_addressing.txt
docs/deviceresource_specification.txt
docs/service_configuration.txt
profiles/SimpleServer.yaml
res/ip/configuration.toml
res/mstp/configuration.toml

Documentation cleanup and minor additions

---

scripts/Dockerfile.alpine-3.9

Use registry running in docker

---

README.md

Specify required CSDK version

---

src/c/CMakeLists.txt

Be more helpful if the SDK isnt found when building (#20)

---

README.md
docs/containerisation.txt

Signed-off-by: Christoffer Christensen <gofling2@hotmail.com>

Documentation on containerisation (Fix: #19)

---

docs/containerisation.txt
scripts/Dockerfile.alpine-3.9
scripts/build.sh
scripts/startup.sh

Signed-off-by: Christoffer Christensen <gofling2@hotmail.com>

Build one docker image for both ip and mstp (#22)

---

Jenkinsfile

Signed-off-by: James Gregg <james.r.gregg@intel.com>

Add Jenkinsfile for new Pipeline build automation

---

scripts/Dockerfile.alpine-3.9
scripts/build_deps.sh

Add License / Attribution files to image (#29)

---

scripts/Dockerfile.alpine-3.9

Add license/copyright labels to container

---

Jenkinsfile
Makefile
scripts/Dockerfile.alpine-3.9
scripts/Dockerfile.alpine-3.9-base

Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>

Update Jenkinsfile to use edgeXBuildCApp

---

scripts/build_deps.sh

What kind of change does this PR introduce?
Service builds against -dev version of the SDK
Issue Number:
Moved to SDK release v1.3.0

ci: move to 1.3.0 release of the SDK

---

GOVERNANCE.md
OWNERS.md
res/ip/configuration.toml
res/mstp/configuration.toml

also added governance.md and owner.md files for LF Edge
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-bacnet-c/blob/master/.github/CONTRIBUTING.md

fix: update all TOML to use quote and not single-quote

---

res/ip/configuration.toml
res/mstp/configuration.toml

Update values in default configuration files to match those of other device services

fix: update default configurations

---

CHANGELOG.md
Makefile
scripts/build_deps.sh

build: move to CSDK v2.3, autogenerate VERSION file

---

CHANGELOG.md
README.md
src/c/main.c

fix: reduce config size to fit within Consul limits

---

CHANGELOG.md
scripts/Dockerfile.alpine
scripts/build_deps.sh

build: move to SDK v3.0.0

---

CHANGELOG.md
scripts/build_deps.sh

1. Set VERSION to 0.0.0 to indicate this is a local dev build and run `make docker` to build the image.
2. From the latest compose-builder run `make device-dev ds-bacnet-ip` 
3. Verify the device-bacnet service bootstrap successfully and contain the following log message:
`level=INFO ts=2023-08-22T09:03:01Z app=device-bacnet-ip msg="EdgeX device SDK for C, version 3.0.2"`

build: move to SDK v3.0.2

---

Attribution.txt

fix: update Attribution.txt

---

scripts/build_deps.sh

build: move to SDK v3.1.0

---

scripts/Dockerfile.alpine
scripts/Dockerfile.alpine-base
scripts/build_deps.sh
src/c/main.c

build: move to SDK v4.0.0-dev.14

---

scripts/build_deps.sh

build: move to SDK v4.0.0

---

res/configuration.yaml

1. make docker
2. run service and check logs

fix: Simplify configuration.yaml
